Repository MCLACS/CSCI452-FA19-Public, pull requests merged in 2019-09, with the labels that each got.

#10 Snippet Table SQL Database
  createDB.sql
Labels: VS1

#12 Create server
  server.js
Labels: VS1

#9 Create html boilerplate
  index.html
Labels: VS1

#23 Get snippet with params
  server.js
Labels: VS2

#21 Added sorting, filtering capabilities to client side
  index.html
Labels: VS2

#27 Added more fake data
  createDB.sql
Labels: VS2

#38 added function to click rows and display SNIP_SNIPPET in modal
  index.html
Labels: VS3

#39 User and prepared procedures
  createDB.sql
  server.js
Labels: VS3
